#!/usr/bin/env bash

if [ $(dpkg-query -W -f='${Status}' ansible 2>/dev/null | grep -c "ok installed") -eq 0 ];
then
    echo "Add APT repositories..."
    export DEBIAN_FRONTEND=noninteractive
    apt-get install -qq software-properties-common &> /dev/null || exit 1
    apt-add-repository -y ppa:ansible/ansible &> /dev/null || exit 1

    echo "Update APT repositories..."
    apt-get update -qq

    echo "Installing Ansible"
    apt-get install -qq ansible &> /dev/null || exit 1
    echo "Ansible installed"

    echo "Installing geerlingguy.mysql from ansible galaxy"
    ansible-galaxy install --roles-path /opt/app/ansible/roles/ geerlingguy.mysql
    echo "geerlinguy.mysql from ansible galaxy installed"
fi

cd /opt/app/ansible
export ANSIBLE_HOST_KEY_CHECKING=False
ansible-playbook $*
