---
- name: Loganalyzer filesystem
  file: path="/opt/loganalyzer-wwwroot" owner="www-data" mode="ug=rwx,o=rx" state="directory"

- name: Loganalyzer package
  unarchive:
    src="loganalyzer/loganalyzer-4.1.3.tar.gz"
    dest="/opt/loganalyzer-wwwroot"

- name: Loganalyzer configuration
  copy: src="loganalyzer/config.php" dest="/opt/loganalyzer-wwwroot/loganalyzer-4.1.3/src/config.php"

- name: Syslog permissions
  file: path="{{ item.path }}" owner="{{ item.owner }}" mode="{{ item.mode }}" state="{{ item.state }}"
  with_items:
    - { path: "/var/log", owner: "root", mode: "ug=rwx,o=rx", state: "directory" }
    - { path: "/var/log/syslog", owner: "root", mode: "ug=rw,o=r", state: "touch" }
